import{a as C,i as p,S as P}from"./assets/vendor-5b071f6a.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const h="/goit-js-hw-12/assets/icon-error-433b5e5d.svg";async function g(){const a="43688767-8e78f2c96043da1155d4d6687",s=new URLSearchParams({key:a,q:y,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:b,page:o}),{data:i}=await C(`https://pixabay.com/api/?${s}`);return i}function f(a){return a.map(({id:s,tags:i,largeImageURL:l,webformatURL:t,comments:r,likes:n,downloads:v,views:w})=>`<li class="gallery-item" id="${s}">
            <a class="gallery-link" href="${l}">
                <img
                    class="gallery-image"
                    src="${t}"
                    alt="${i}"
                    />               
            </a>
            <ul class="gallery-stat-list">
                    <li class="stat-item"><h2 class="title">Likes</h2><p class="stat-data">${n}</p></li>
                    <li class="stat-item"><h2 class="title">Views</h2><p class="stat-data">${w}</p></li>
                    <li class="stat-item"><h2 class="title">Comments</h2><p class="stat-data">${r}</p></li>
                    <li class="stat-item"><h2 class="title">Downloads</h2><p class="stat-data">${v}</p></li>
            </ul>
            
        </li>`).join("")}const e={form:document.querySelector(".task-form"),input:document.querySelector(".form-input"),list:document.querySelector(".gallery"),loadWrapp:document.querySelector(".wrapper-btn"),loadBtn:document.querySelector(".load-btn")};let y=null;const b=15;let o=1,c=null,m=null,d=null;const B="Please enter your search query, the field cannot be blank!",q="Sorry, there are no images matching your search query. Please try again!",z="We're sorry, but you've reached the end of search results.";e.form.addEventListener("submit",$);e.loadBtn.addEventListener("click",M);async function $(a){a.preventDefault(),o=1,e.loadBtn.classList.add("is-hidden");const s=e.input.value.trim();if(!s){e.list.innerHTML="",u(B);return}y=s,e.list.innerHTML='<span class="loader"></span>',await g().then(i=>{if(!i.hits.length){e.list.innerHTML="",u(q);return}e.list.innerHTML=f(i.hits),S.refresh(),c=e.list.firstChild.getBoundingClientRect().height*2,window.scrollBy({top:c,behavior:"smooth"}),o+=1,m=i.totalHits,d=Math.ceil(m/b),o<=d&&e.loadBtn.classList.remove("is-hidden")}).catch(i=>{L(i)}),e.form.reset()}async function M(a){e.loadBtn.classList.add("is-hidden"),e.loadWrapp.insertAdjacentHTML("beforeend",'<span class="loader"></span>'),await g().then(s=>{if(e.list.insertAdjacentHTML("beforeend",f(s.hits)),S.refresh(),window.scrollBy({top:c,behavior:"smooth"}),o+=1,e.loadWrapp.lastChild.remove(),o>d){u(z);return}e.loadBtn.classList.remove("is-hidden")}).catch(s=>{e.loadWrapp.lastChild.remove(),L(s)})}function u(a){return e.loadBtn.classList.add("is-hidden"),p.error({...T,message:a,backgroundColor:"rgb(239, 64, 64)",iconUrl:h})}function L(a){return p.error({...E,message:`${a}`,backgroundColor:"rgb(239, 64, 64)",iconUrl:h})}const T={id:"myIziToast",title:"Warning",titleColor:"rgb(255, 255, 255)",titleSize:"16",messageColor:"rgb(255, 255, 255)",messageSize:"16",position:"topRight"},E={id:"myIziToast",title:"Error",titleColor:"rgb(255, 255, 255)",titleSize:"16",messageColor:"rgb(255, 255, 255)",messageSize:"16",position:"topCenter"},S=new P(".gallery-item a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
