import{a as S,i as v,S as w}from"./assets/vendor-5b071f6a.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const P="/goit-js-hw-12/assets/icon-error-433b5e5d.svg";async function m(){const i="43688767-8e78f2c96043da1155d4d6687",s=new URLSearchParams({key:i,q:f,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g,page:o}),{data:r}=await S(`https://pixabay.com/api/?${s}`);return r}function p(i){return i.map(({id:s,tags:r,largeImageURL:l,webformatURL:e,comments:a,likes:n,downloads:b,views:L})=>`<li class="gallery-item" id="${s}">
            <a class="gallery-link" href="${l}">
                <img
                    class="gallery-image"
                    src="${e}"
                    alt="${r}"
                    />               
            </a>
            <ul class="gallery-stat-list">
                    <li class="stat-item"><h2 class="title">Likes</h2><p class="stat-data">${n}</p></li>
                    <li class="stat-item"><h2 class="title">Views</h2><p class="stat-data">${L}</p></li>
                    <li class="stat-item"><h2 class="title">Comments</h2><p class="stat-data">${a}</p></li>
                    <li class="stat-item"><h2 class="title">Downloads</h2><p class="stat-data">${b}</p></li>
            </ul>
            
        </li>`).join("")}const t={form:document.querySelector(".task-form"),input:document.querySelector(".form-input"),list:document.querySelector(".gallery"),loadWrapp:document.querySelector(".wrapper-btn"),loadBtn:document.querySelector(".load-btn")};let f=null;const g=15;let o=1,c=null,h=null,d=null;const B="Please enter your search query, the field cannot be blank!",q="Sorry, there are no images matching your search query. Please try again!",M="We're sorry, but you've reached the end of search results.";t.form.addEventListener("submit",$);t.loadBtn.addEventListener("click",C);async function $(i){i.preventDefault(),o=1,t.loadBtn.classList.add("is-hidden");const s=t.input.value.trim();if(!s){t.list.innerHTML="",u(B);return}f=s,t.list.innerHTML='<span class="loader"></span>',await m().then(r=>{if(!r.hits.length){t.list.innerHTML="",u(q);return}t.list.innerHTML=p(r.hits),y.refresh(),c=t.list.firstChild.getBoundingClientRect().height*2,window.scrollBy({top:c,behavior:"smooth"}),o+=1,h=r.totalHits,d=Math.ceil(h/g),o<=d&&t.loadBtn.classList.remove("is-hidden")}).catch(r=>console.log("catch",r)),t.form.reset()}async function C(i){t.loadBtn.classList.add("is-hidden"),t.loadWrapp.insertAdjacentHTML("beforeend",'<span class="loader"></span>'),await m().then(s=>{if(t.list.insertAdjacentHTML("beforeend",p(s.hits)),y.refresh(),window.scrollBy({top:c,behavior:"smooth"}),o+=1,t.loadWrapp.lastChild.remove(),o>d){u(M);return}t.loadBtn.classList.remove("is-hidden")}).catch(s=>console.log("catch",s))}function u(i){return t.loadBtn.classList.add("is-hidden"),v.error({...T,message:i,backgroundColor:"rgb(239, 64, 64)",iconUrl:P})}const T={id:"myIziToast",title:"Warning",titleColor:"rgb(255, 255, 255)",titleSize:"16",messageColor:"rgb(255, 255, 255)",messageSize:"16",position:"topRight"},y=new w(".gallery-item a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
